server:
  port: 7078
  servlet:
    context-path: /invoices

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:25001/eureka/

spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/ceefac_factures
    username: sigec
    password: Sigec@Ceenet2020
  mail:
    host: smtp.gmail.com
    port: 587
    username: device@ceenettechnologies.com
    password: device@2021
    properties.mail.smtp:
      auth: true
      starttls.enable: true
    


logging:
  level:
    root: ERROR
    org.springframework: ERROR
    com.ceenet.ceefac.ws: DEBUG
    org.hibernate.type: ERROR
  pattern:
    console: "%d{yyyy-mm-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"

